### YamlMime:ManagedReference
items:
- uid: QL.Engine.AppConfig
  commentId: T:QL.Engine.AppConfig
  id: AppConfig
  parent: QL.Engine
  children:
  - QL.Engine.AppConfig.Debug
  - QL.Engine.AppConfig.MaxConcurrency
  - QL.Engine.AppConfig.OutputFile
  - QL.Engine.AppConfig.OutputFormat
  - QL.Engine.AppConfig.Sync
  langs:
  - csharp
  - vb
  name: AppConfig
  nameWithType: AppConfig
  fullName: QL.Engine.AppConfig
  type: Class
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: AppConfig
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 2
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public class AppConfig
    content.vb: Public Class AppConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.QL.Engine.Extensions.ObjectExtensions.ToDictionary
- uid: QL.Engine.AppConfig.Debug
  commentId: P:QL.Engine.AppConfig.Debug
  id: Debug
  parent: QL.Engine.AppConfig
  langs:
  - csharp
  - vb
  name: Debug
  nameWithType: AppConfig.Debug
  fullName: QL.Engine.AppConfig.Debug
  type: Property
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: Debug
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 4
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public bool Debug { get; init; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Debug As Boolean
  overload: QL.Engine.AppConfig.Debug*
- uid: QL.Engine.AppConfig.Sync
  commentId: P:QL.Engine.AppConfig.Sync
  id: Sync
  parent: QL.Engine.AppConfig
  langs:
  - csharp
  - vb
  name: Sync
  nameWithType: AppConfig.Sync
  fullName: QL.Engine.AppConfig.Sync
  type: Property
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: Sync
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 5
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public bool Sync { get; init; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Sync As Boolean
  overload: QL.Engine.AppConfig.Sync*
- uid: QL.Engine.AppConfig.MaxConcurrency
  commentId: P:QL.Engine.AppConfig.MaxConcurrency
  id: MaxConcurrency
  parent: QL.Engine.AppConfig
  langs:
  - csharp
  - vb
  name: MaxConcurrency
  nameWithType: AppConfig.MaxConcurrency
  fullName: QL.Engine.AppConfig.MaxConcurrency
  type: Property
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: MaxConcurrency
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 6
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public int MaxConcurrency { get; init; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxConcurrency As Integer
  overload: QL.Engine.AppConfig.MaxConcurrency*
- uid: QL.Engine.AppConfig.OutputFormat
  commentId: P:QL.Engine.AppConfig.OutputFormat
  id: OutputFormat
  parent: QL.Engine.AppConfig
  langs:
  - csharp
  - vb
  name: OutputFormat
  nameWithType: AppConfig.OutputFormat
  fullName: QL.Engine.AppConfig.OutputFormat
  type: Property
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: OutputFormat
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 7
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public OutputFormat OutputFormat { get; init; }
    parameters: []
    return:
      type: QL.Engine.OutputFormat
    content.vb: Public Property OutputFormat As OutputFormat
  overload: QL.Engine.AppConfig.OutputFormat*
- uid: QL.Engine.AppConfig.OutputFile
  commentId: P:QL.Engine.AppConfig.OutputFile
  id: OutputFile
  parent: QL.Engine.AppConfig
  langs:
  - csharp
  - vb
  name: OutputFile
  nameWithType: AppConfig.OutputFile
  fullName: QL.Engine.AppConfig.OutputFile
  type: Property
  source:
    remote:
      path: src/QL.Engine/AppConfig.cs
      branch: main
      repo: git@github.com:rszemplinski/qlsh.git
    id: OutputFile
    path: ../src/QL.Engine/AppConfig.cs
    startLine: 8
  assemblies:
  - qlsh
  namespace: QL.Engine
  syntax:
    content: public string? OutputFile { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property OutputFile As String
  overload: QL.Engine.AppConfig.OutputFile*
references:
- uid: QL.Engine
  commentId: N:QL.Engine
  href: QL.html
  name: QL.Engine
  nameWithType: QL.Engine
  fullName: QL.Engine
  spec.csharp:
  - uid: QL
    name: QL
    href: QL.html
  - name: .
  - uid: QL.Engine
    name: Engine
    href: QL.Engine.html
  spec.vb:
  - uid: QL
    name: QL
    href: QL.html
  - name: .
  - uid: QL.Engine
    name: Engine
    href: QL.Engine.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.QL.Engine.Extensions.ObjectExtensions.ToDictionary
  commentId: M:QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
  parent: QL.Engine.Extensions.ObjectExtensions
  definition: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
  href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  name: ToDictionary(object)
  nameWithType: ObjectExtensions.ToDictionary(object)
  fullName: QL.Engine.Extensions.ObjectExtensions.ToDictionary(object)
  nameWithType.vb: ObjectExtensions.ToDictionary(Object)
  fullName.vb: QL.Engine.Extensions.ObjectExtensions.ToDictionary(Object)
  name.vb: ToDictionary(Object)
  spec.csharp:
  - uid: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
    name: ToDictionary
    href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
    name: ToDictionary
    href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
  commentId: M:QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
  isExternal: true
  href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  name: ToDictionary(object)
  nameWithType: ObjectExtensions.ToDictionary(object)
  fullName: QL.Engine.Extensions.ObjectExtensions.ToDictionary(object)
  nameWithType.vb: ObjectExtensions.ToDictionary(Object)
  fullName.vb: QL.Engine.Extensions.ObjectExtensions.ToDictionary(Object)
  name.vb: ToDictionary(Object)
  spec.csharp:
  - uid: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
    name: ToDictionary
    href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: QL.Engine.Extensions.ObjectExtensions.ToDictionary(System.Object)
    name: ToDictionary
    href: QL.Engine.Extensions.ObjectExtensions.html#QL_Engine_Extensions_ObjectExtensions_ToDictionary_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: QL.Engine.Extensions.ObjectExtensions
  commentId: T:QL.Engine.Extensions.ObjectExtensions
  parent: QL.Engine.Extensions
  href: QL.Engine.Extensions.ObjectExtensions.html
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: QL.Engine.Extensions.ObjectExtensions
- uid: QL.Engine.Extensions
  commentId: N:QL.Engine.Extensions
  href: QL.html
  name: QL.Engine.Extensions
  nameWithType: QL.Engine.Extensions
  fullName: QL.Engine.Extensions
  spec.csharp:
  - uid: QL
    name: QL
    href: QL.html
  - name: .
  - uid: QL.Engine
    name: Engine
    href: QL.Engine.html
  - name: .
  - uid: QL.Engine.Extensions
    name: Extensions
    href: QL.Engine.Extensions.html
  spec.vb:
  - uid: QL
    name: QL
    href: QL.html
  - name: .
  - uid: QL.Engine
    name: Engine
    href: QL.Engine.html
  - name: .
  - uid: QL.Engine.Extensions
    name: Extensions
    href: QL.Engine.Extensions.html
- uid: QL.Engine.AppConfig.Debug*
  commentId: Overload:QL.Engine.AppConfig.Debug
  href: QL.Engine.AppConfig.html#QL_Engine_AppConfig_Debug
  name: Debug
  nameWithType: AppConfig.Debug
  fullName: QL.Engine.AppConfig.Debug
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: QL.Engine.AppConfig.Sync*
  commentId: Overload:QL.Engine.AppConfig.Sync
  href: QL.Engine.AppConfig.html#QL_Engine_AppConfig_Sync
  name: Sync
  nameWithType: AppConfig.Sync
  fullName: QL.Engine.AppConfig.Sync
- uid: QL.Engine.AppConfig.MaxConcurrency*
  commentId: Overload:QL.Engine.AppConfig.MaxConcurrency
  href: QL.Engine.AppConfig.html#QL_Engine_AppConfig_MaxConcurrency
  name: MaxConcurrency
  nameWithType: AppConfig.MaxConcurrency
  fullName: QL.Engine.AppConfig.MaxConcurrency
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: QL.Engine.AppConfig.OutputFormat*
  commentId: Overload:QL.Engine.AppConfig.OutputFormat
  href: QL.Engine.AppConfig.html#QL_Engine_AppConfig_OutputFormat
  name: OutputFormat
  nameWithType: AppConfig.OutputFormat
  fullName: QL.Engine.AppConfig.OutputFormat
- uid: QL.Engine.OutputFormat
  commentId: T:QL.Engine.OutputFormat
  parent: QL.Engine
  href: QL.Engine.OutputFormat.html
  name: OutputFormat
  nameWithType: OutputFormat
  fullName: QL.Engine.OutputFormat
- uid: QL.Engine.AppConfig.OutputFile*
  commentId: Overload:QL.Engine.AppConfig.OutputFile
  href: QL.Engine.AppConfig.html#QL_Engine_AppConfig_OutputFile
  name: OutputFile
  nameWithType: AppConfig.OutputFile
  fullName: QL.Engine.AppConfig.OutputFile
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
